version: "3"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=misr.xyz
      - SUBDOMAINS=www,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=true #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./appdata:/config
    depends_on:
      - wordpress
      - nextcloud
      - gitlab
      - stock-crawler
      - piwigo
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=neverknow
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
  
  # stockCrawler
  stock-crawler:
    depends_on: 
      - mariadb
    environment:
      - GIT_URL=https://misr.xyz/gitlab/misr/stock-server
    build: ./nodeApp
    container_name: stockCrawler
    restart: unless-stopped

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=neverknow
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nc_user
      - MYSQL_PASSWORD=nc_password
    volumes:
      - ./nextcloud/config:/config/www/nextcloud/config/
      - ./nextcloud/data:/data
    depends_on: 
      - mariadb
    restart: unless-stopped

  # Wordpress Setup
  wordpress:
    depends_on: 
      - mariadb
    build: ./wordpress
    container_name: wordpress
    environment:
      - WP_SUBDIRECTORY=burogu
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_CONFIG_EXTRA=
        define('WP_HOME','https://misr.xyz/burogu');
        define('WP_SITEURL','https://misr.xyz/burogu');
    restart: unless-stopped

  notebook:
    image: jupyter/datascience-notebook
    container_name: notebook
    volumes:
      - ./work:/home/jovyan/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    command: start-notebook.sh --NotebookApp.token='anhnt123' --NotebookApp.base_url=/notebook

  # Gitlab Setup
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    volumes:
      - ./gitlab/config:/etc/gitlab:Z
      - ./gitlab/logs:/var/log/gitlab:Z
      - ./gitlab/data:/var/opt/gitlab:Z
      - ./gitlab/backups:/mnt/backups/gitlab:Z
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # URL
        external_url 'http://misr.xyz/gitlab'
        # Backup directory
        gitlab_rails['backup_path'] = '/mnt/backups/gitlab'
        # Timezone
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        # E-mail
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "user@gmail.com"
        gitlab_rails['smtp_password'] = "PASSWORD"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer' # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
      # Add any other gitlab.rb configuration here, each on its own line
      GITLAB_RELATIVE_URL_ROOT: /gitlab

  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: piwigo
    # build: ./piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./piwigo:/config/nginx/site-confs
    restart: unless-stopped

  adguard:
    container_name: adguard 
    domainname: docker
    hostname: adguard
    image: adguard/adguardhome:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '853:853/tcp'
      - '3000:3000/tcp'
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
      - ./adguard/certs:/opt/adguardhome/certs:ro
      
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     # - "53:53/tcp"
  #     # - "53:53/udp"
  #     - "67:67/udp"
  #   environment:
  #     TZ: 'America/Chicago'
  #     WEBPASSWORD: 'anhnt123'
  #   # Volumes store your data between container upgrades
  #   volumes:
  #     - './pihole/etc-pihole/:/etc/pihole/'
  #     - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
  #   # Recommended but not required (DHCP needs NET_ADMIN)
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # redmine:
  #   image: sameersbn/redmine:latest
  #   environment:
  #     DB_ADAPTER: postgresql
  #     DB_HOST: redmine_postgres
  #     DB_NAME: redmine
  #     DB_USER: redmine
  #     DB_PASS: redmine
  #     MEMCACHE_HOST: redmine_memcached
  #     SMTP_USER: user@gmail.com
  #     SMTP_PASS: PASSWORD
  #     REDMINE_BACKUPS_DIR: /home/redmine/backups
  #     REDMINE_RELATIVE_URL_ROOT: /redmine
  #   volumes:
  #     - redmine_data:/home/redmine/data
  #     - gitlab_data:/home/redmine/gitlab:ro
  #     - ./backups/redmine:/home/redmine/backupsroot
  #   depends_on:
  #     - redmine_postgres
  #   restart: unless-stopped

  # redmine_postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: redmine
  #     POSTGRES_PASSWORD: redmine
  #     POSTGRES_DB: redmine
  #   volumes:
  #     - redmine_postgresql_data:/var/lib/postgresql/data:rw
  #   restart: unless-stopped

  # redmine_memcached:
  #   image: memcached:latest

  # jenkins:
  #   image: jenkins:latest
  #   ports:
  #     - "50000:50000"
  #   environment:
  #     JENKINS_OPTS: "--prefix=/jenkins"
  #   volumes:
  #     - jenkins_data:/var/jenkins_home
  #     - ./backups/jenkins:/backups

