version: '3'

services:
  wordpress_db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wp_db
      - MYSQL_ROOT_PASSWORD=wp_password
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
      
  wordpress:
    depends_on: 
      - wordpress_db
    image: wordpress:php7.4-apache
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=wordpress_db:3306
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_CONFIG_EXTRA=
        define('WP_HOME','http://localhost/blog');
        define('WP_SITEURL','http://localhost/blog');
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html/blog
      - ./nginx-conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge