version: "3"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=neverknow
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  node-js-app:
    build: ./nodeApp
    container_name: NodeJSApp
    environment:
      - GIT_URL=https://misr.xyz/gitlab/misr/stock-server
    restart: unless-stopped
    depends_on: 
      - mariadb

